config:
  target: "http://localhost:8888"
  phases:
    - duration: 60
      arrivalRate: 20
  defaults:
    headers:
      Content-Type: "application/json"
scenarios:
  - flow:
    - get:
        url: "/get/test-key"
        capture:
          - json: "$.timestamp"
            as: "startTime"
    - think: 1
    - log: "Latency: {{ Math.round((Date.now() - startTime)) }}ms"